name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: martinkey
          password: ${{ secrets.SECRET }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gostartups/ubuntu-leveldb4.8:latest
